services:
  cockpit:
    build: .
    container_name: cockpit
    ports:
      - 8000:80
    volumes:
      - ./cockpit/storage:/var/www/html/storage
      - ./cockpit/config:/var/www/html/config
      - ./cockpit/.spaces:/var/www/html/.spaces
      - cockpit_storage:/storage
      - cockpit_config:/config
      - cockpit_spaces:/.spaces

volumes:
  cockpit_storage:
  cockpit_config:
  cockpit_spaces: