name: Pipeline Frontend
run-name: 🚀 Usuário ( ${{ github.actor }} ) Branch ( ${{ github.ref_name }} )  🚀

on:
    push:
        branches:
        - main
    pull_request:
        branches:
        - main 

jobs:
    Build:
        runs-on: ubuntu-latest
        steps:
          - name: Checkout Project
            uses: actions/checkout@v2

          - name: Log in to Docker Hub
            uses: docker/login-action@v1
            with:
              username: ${{ secrets.DOCKER_LOGIN }}
              password: ${{ secrets.DOCKER_PASSWORD }}
          
          - name: Read version from package.json
            id: get_project_version
            run: |
              VERSION=$(cat package.json | jq -r '.version')
              echo "VERSION=$VERSION" >> $GITHUB_ENV
              echo "Project Version $VERSION"

          - name: Build Docker image
            uses: docker/build-push-action@v6
            with:
              context: .
              file: ./Dockerfile
              push: true
              target: deploy
              tags: |
                ${{ secrets.DOCKER_LOGIN }}/multitreine:frontend-${{ env.VERSION }}
                ${{ secrets.DOCKER_LOGIN }}/multitreine:frontend-latest
              build-args: |
                COCKPIT_URL=${{ secrets.COCKPIT_URL }}
                COCKPIT_API_KEY_LP=${{ secrets.COCKPIT_API_KEY_LP }}